apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-agent
  namespace: default
  labels:
    name: kubernetes-agent
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat    
    tty: true
    # resources:
    #   limits:
    #     memory: "512Mi"
    #     cpu: "500m"
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/key.json
    volumeMounts:
    - name: kaniko-secret
      mountPath: /secret
  - name: maven
    image: maven:3.6.0-jdk-8
    securityContext:
      privileged: false   	
    command:
    - cat
    tty: true  
    # resources:
    #   limits:
    #     memory: "512Mi"
    #     cpu: "500m"
  volumes:
      - name: kaniko-secret
        secret:
          secretName: kaniko-secret
