apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-agent
  namespace: default
  labels:
    name: kubernetes-agent
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat    
    tty: true
    # resources:
    #   limits:
    #     memory: "512Mi"
    #     cpu: "500m"
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/ 
  - name: maven
    image: maven:3.6.0-jdk-8
    securityContext:
      privileged: false   	
    command:
    - cat
    tty: true  
    # resources:
    #   limits:
    #     memory: "512Mi"
    #     cpu: "500m"
  volumes:
      - name: docker-config
        secret:
          secretName: dockerhub-secret
