apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-agent
  namespace: default
  labels:
    name: kubernetes-agent
spec:
  containers:
  # - name: kaniko
  #   image: gcr.io/kaniko-project/executor:debug
  #   command:
  #   - /busybox/cat    
  #   tty: true
  #   volumeMounts:
  #     - name: acr-secret
  #       mountPath: /kaniko/.docker/ 
  - name: maven
    image: maven:3.6.0-jdk-8
    securityContext:
      privileged: false   	
    command:
    - cat
    tty: true  
  # volumes:
  #     - name: acr-secret
  #       secret:
  #         secretName: acr-secret  
